<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CareerJob;

class CareerJobSeeder extends Seeder
{
    /**
     * Run the database seeds with the EXACT 21 default jobs from Figma design.
     */
    public function run(): void
    {
        $jobs = [
            // Card 1
            [
                'id' => 1,
                'title' => 'Content Creator',
                'major' => 'DKV',
                'salary' => 'Rp 1.5 Juta',
                'work_location' => 'Hybrid',
                'work_type' => 'Contract',
                'company_name' => 'Digideep',
                'company_logo_char' => 'D',
                'company_img' => 'assets/partners/Digdeep.avif',
                'company_bg' => 'bg-indigo-600',
                'location' => 'Greater Jakarta',
                'location_group' => 'Jabodetabek',
                'posted_time' => '1 hari yang lalu',
                'post_time_category' => 'Hari ini',
                'is_active' => true,
            ],
            // Card 2
            [
                'id' => 2,
                'title' => 'UI/UX Developer',
                'major' => 'DKV',
                'salary' => 'Rp 1.5 Juta',
                'work_location' => 'Hybrid',
                'work_type' => 'Contract',
                'company_name' => 'Tenos Data Teknologi',
                'company_logo_char' => 'T',
                'company_img' => 'assets/partners/tenos-data-teknologi.avif',
                'company_bg' => 'bg-amber-500',
                'location' => 'Greater Jakarta',
                'location_group' => 'Jabodetabek',
                'posted_time' => '2 hari yang lalu',
                'post_time_category' => 'Minggu ini',
                'is_active' => true,
            ],
            // Card 3
            [
                'id' => 3,
                'title' => 'Digital Marketing',
                'major' => 'DKV',
                'salary' => 'Rp 1.5 Juta',
                'work_location' => 'Hybrid',
                'work_type' => 'Contract',
                'company_name' => 'Indekstat',
                'company_logo_char' => 'I',
                'company_img' => 'assets/partners/indekstat.avif',
                'company_bg' => 'bg-orange-500',
                'location' => 'Greater Jakarta',
                'location_group' => 'Jabodetabek',
                'posted_time' => '3 hari yang lalu',
                'post_time_category' => 'Minggu ini',
                'is_active' => true,
            ],
            // Card 4
            [
                'id' => 4,
                'title' => 'Frontend Developer',
                'major' => 'RPL',
                'salary' => 'Rp 2 Juta',
                'work_location' => 'Onsite',
                'work_type' => 'Full-time',
                'company_name' => 'Alfahuma Rekayasa Teknologi',
                'company_logo_char' => 'A',
                'company_img' => 'assets/partners/alfahuma-rekayasa.avif',
                'company_bg' => 'bg-blue-600',
                'location' => 'Bekasi, West Java',
                'location_group' => 'Jawa',
                'posted_time' => '4 hari yang lalu',
                'post_time_category' => 'Minggu ini',
                'is_active' => true,
            ],
            // Card 5
            [
                'id' => 5,
                'title' => 'IT Support',
                'major' => 'TKJ',
                'salary' => 'Rp 3 Juta',
                'work_location' => 'Remote/WFH',
                'work_type' => 'Part-time',
                'company_name' => 'Pertamina',
                'company_logo_char' => 'P',
                'company_img' => 'assets/partners/pertamina.avif',
                'company_bg' => 'bg-red-600',
                'location' => 'Central Jakarta, DKI Jakarta',
                'location_group' => 'Jabodetabek',
                'posted_time' => '5 hari yang lalu',
                'post_time_category' => 'Minggu ini',
                'is_active' => true,
            ],
            // Card 6
            [
                'id' => 6,
                'title' => 'Network Administrator',
                'major' => 'TKJ',
                'salary' => 'Rp 2.5 Juta',
                'work_location' => 'Onsite',
                'work_type' => 'Freelance',
                'company_name' => 'Vektora Studio',
                'company_logo_char' => 'V',
                'company_img' => 'assets/partners/vektora-studio.avif',
                'company_bg' => 'bg-emerald-600',
                'location' => 'Surakarta, Central Java',
                'location_group' => 'Jawa',
                'posted_time' => '6 hari yang lalu',
                'post_time_category' => 'Minggu ini',
                'is_active' => true,
            ],
            // Card 7
            [
                'id' => 7,
                'title' => 'Cloud Engineer',
                'major' => 'TKJ',
                'salary' => 'Rp 1 Juta',
                'work_location' => 'Remote/WFH',
                'work_type' => 'Internship',
                'company_name' => 'PLN',
                'company_logo_char' => 'P',
                'company_img' => 'assets/partners/pln-1.avif',
                'company_bg' => 'bg-cyan-600',
                'location' => 'South Jakarta, DKI Jakarta',
                'location_group' => 'Jabodetabek',
                'posted_time' => '7 hari yang lalu',
                'post_time_category' => 'Minggu ini',
                'is_active' => true,
            ],
            // Card 8
            [
                'id' => 8,
                'title' => 'Video Editor',
                'major' => 'DKV',
                'salary' => 'Rp 2 Juta',
                'work_location' => 'Hybrid',
                'work_type' => 'Part-time',
                'company_name' => 'Telkom Indonesia',
                'company_logo_char' => 'T',
                'company_img' => 'assets/partners/telkom-id.avif',
                'company_bg' => 'bg-red-600',
                'location' => 'South Jakarta, DKI Jakarta',
                'location_group' => 'Jabodetabek',
                'posted_time' => '8 hari yang lalu',
                'post_time_category' => 'Bulan ini',
                'is_active' => true,
            ],
            // Card 9
            [
                'id' => 9,
                'title' => 'Web Developer',
                'major' => 'RPL',
                'salary' => 'Rp 1.5 Juta',
                'work_location' => 'Onsite',
                'work_type' => 'Contract',
                'company_name' => 'Toyota Astra Motor',
                'company_logo_char' => 'T',
                'company_img' => 'assets/partners/toyota-astra-motor.avif',
                'company_bg' => 'bg-rose-700',
                'location' => 'Central Jakarta, DKI Jakarta',
                'location_group' => 'Jabodetabek',
                'posted_time' => '9 hari yang lalu',
                'post_time_category' => 'Bulan ini',
                'is_active' => true,
            ],
            // Card 10
            [
                'id' => 10,
                'title' => 'Graphic Designer',
                'major' => 'DKV',
                'salary' => 'Rp 5 Juta',
                'work_location' => 'Hybrid',
                'work_type' => 'Full-time',
                'company_name' => 'Sisindokom Lintasbuana',
                'company_logo_char' => 'S',
                'company_img' => 'assets/partners/sisindokom-1.avif',
                'company_bg' => 'bg-purple-600',
                'location' => 'Central Jakarta, DKI Jakarta',
                'location_group' => 'Jabodetabek',
                'posted_time' => '10 hari yang lalu',
                'post_time_category' => 'Bulan ini',
                'is_active' => true,
            ],
            // Card 11
            [
                'id' => 11,
                'title' => 'Backend Developer',
                'major' => 'RPL',
                'salary' => 'Rp 2 Juta',
                'work_location' => 'Onsite',
                'work_type' => 'Freelance',
                'company_name' => 'Yaksa Ersada Solusindo',
                'company_logo_char' => 'Y',
                'company_img' => 'assets/partners/yaksa-ersada.avif',
                'company_bg' => 'bg-red-500',
                'location' => 'Bekasi, West Java',
                'location_group' => 'Jawa',
                'posted_time' => '11 hari yang lalu',
                'post_time_category' => 'Bulan ini',
                'is_active' => true,
            ],
            // Card 12
            [
                'id' => 12,
                'title' => 'Security Engineer',
                'major' => 'TKJ',
                'salary' => 'Rp 4 Juta',
                'work_location' => 'Remote/WFH',
                'work_type' => 'Part-time',
                'company_name' => 'Telkom Akses',
                'company_logo_char' => 'T',
                'company_img' => 'assets/partners/telkom-akses.avif',
                'company_bg' => 'bg-red-600',
                'location' => 'Tangerang, Banten',
                'location_group' => 'Jabodetabek',
                'posted_time' => '12 hari yang lalu',
                'post_time_category' => 'Bulan ini',
                'is_active' => true,
            ],
            // Card 13
            [
                'id' => 13,
                'title' => 'IT Support',
                'major' => 'TKJ',
                'salary' => 'Rp 4 Juta',
                'work_location' => 'Onsite',
                'work_type' => 'Contract',
                'company_name' => 'Sucofindo',
                'company_logo_char' => 'S',
                'company_img' => 'assets/partners/Sucofindo.avif',
                'company_bg' => 'bg-blue-700',
                'location' => 'South Jakarta, DKI Jakarta',
                'location_group' => 'Jabodetabek',
                'posted_time' => '13 hari yang lalu',
                'post_time_category' => 'Bulan ini',
                'is_active' => true,
            ],
            // Card 14
            [
                'id' => 14,
                'title' => '3D Designer',
                'major' => 'DKV',
                'salary' => 'Rp 3 Juta',
                'work_location' => 'Hybrid',
                'work_type' => 'Part-time',
                'company_name' => 'Pelabuhan Indonesia',
                'company_logo_char' => 'P',
                'company_img' => 'assets/partners/pelabuhanIndo.avif',
                'company_bg' => 'bg-sky-600',
                'location' => 'North Jakarta, DKI Jakarta',
                'location_group' => 'Jabodetabek',
                'posted_time' => '14 hari yang lalu',
                'post_time_category' => 'Bulan ini',
                'is_active' => true,
            ],
            // Card 15
            [
                'id' => 15,
                'title' => 'Fullstack Developer',
                'major' => 'RPL',
                'salary' => 'Rp 1 Juta',
                'work_location' => 'Remote/WFH',
                'work_type' => 'Freelance',
                'company_name' => 'Tokopedia',
                'company_logo_char' => 'T',
                'company_img' => 'assets/partners/tokped.avif',
                'company_bg' => 'bg-emerald-600',
                'location' => 'South Jakarta, DKI Jakarta',
                'location_group' => 'Jabodetabek',
                'posted_time' => '15 hari yang lalu',
                'post_time_category' => 'Bulan ini',
                'is_active' => true,
            ],
            // Card 16
            [
                'id' => 16,
                'title' => 'QA Tester',
                'major' => 'RPL',
                'salary' => 'Rp 1.5 Juta',
                'work_location' => 'Remote/WFH',
                'work_type' => 'Full-time',
                'company_name' => 'Shopee',
                'company_logo_char' => 'S',
                'company_img' => 'assets/partners/Shoppie.avif',
                'company_bg' => 'bg-orange-600',
                'location' => 'South Jakarta, DKI Jakarta',
                'location_group' => 'Jabodetabek',
                'posted_time' => '16 hari yang lalu',
                'post_time_category' => 'Bulan ini',
                'is_active' => true,
            ],
            // Card 17
            [
                'id' => 17,
                'title' => 'Animator',
                'major' => 'DKV',
                'salary' => 'Rp 2.5 Juta',
                'work_location' => 'Onsite',
                'work_type' => 'Internship',
                'company_name' => 'Lazada',
                'company_logo_char' => 'L',
                'company_img' => 'assets/partners/lazada.avif',
                'company_bg' => 'bg-purple-600',
                'location' => 'South Jakarta, DKI Jakarta',
                'location_group' => 'Jabodetabek',
                'posted_time' => '17 hari yang lalu',
                'post_time_category' => 'Bulan ini',
                'is_active' => true,
            ],
            // Card 18
            [
                'id' => 18,
                'title' => 'Network Administrator',
                'major' => 'TKJ',
                'salary' => 'Rp 3.5 Juta',
                'work_location' => 'Hybrid',
                'work_type' => 'Part-time',
                'company_name' => 'Gojek',
                'company_logo_char' => 'G',
                'company_img' => 'assets/partners/gojek.avif',
                'company_bg' => 'bg-emerald-600',
                'location' => 'South Jakarta, DKI Jakarta',
                'location_group' => 'Jabodetabek',
                'posted_time' => '18 hari yang lalu',
                'post_time_category' => 'Bulan ini',
                'is_active' => true,
            ],
            // Card 19
            [
                'id' => 19,
                'title' => 'Backend Developer',
                'major' => 'RPL',
                'salary' => 'Rp 6 Juta',
                'work_location' => 'Hybrid',
                'work_type' => 'Contract',
                'company_name' => 'Grab',
                'company_logo_char' => 'G',
                'company_img' => 'assets/partners/grab.avif',
                'company_bg' => 'bg-emerald-700',
                'location' => 'South Jakarta, DKI Jakarta',
                'location_group' => 'Jabodetabek',
                'posted_time' => '19 hari yang lalu',
                'post_time_category' => 'Bulan ini',
                'is_active' => true,
            ],
            // Card 20
            [
                'id' => 20,
                'title' => 'UI/UX Designer',
                'major' => 'DKV',
                'salary' => 'Rp 1 Juta',
                'work_location' => 'Onsite',
                'work_type' => 'Freelance',
                'company_name' => 'Maxim',
                'company_logo_char' => 'M',
                'company_img' => 'assets/partners/Maxim.avif',
                'company_bg' => 'bg-amber-400 text-black',
                'location' => 'South Jakarta, DKI Jakarta',
                'location_group' => 'Jabodetabek',
                'posted_time' => '20 hari yang lalu',
                'post_time_category' => 'Bulan ini',
                'is_active' => true,
            ],
            // Card 21
            [
                'id' => 21,
                'title' => 'Cloud Engineer',
                'major' => 'TKJ',
                'salary' => 'Rp 3 Juta',
                'work_location' => 'Remote/WFH',
                'work_type' => 'Full-time',
                'company_name' => 'Blibli',
                'company_logo_char' => 'B',
                'company_img' => 'assets/partners/blibli.avif',
                'company_bg' => 'bg-blue-500',
                'location' => 'Central Jakarta, DKI Jakarta',
                'location_group' => 'Jabodetabek',
                'posted_time' => '21 hari yang lalu',
                'post_time_category' => 'Bulan ini',
                'is_active' => true,
            ],
        ];

        // Truncate or clean table first to remove wrong entries
        CareerJob::truncate();

        foreach ($jobs as $job) {
            CareerJob::create($job);
        }
    }
}
